###################################################################

# Created by write_sdc on Fri Oct  9 20:38:53 2026

###################################################################
set sdc_version 2.2

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_load -pin_load 2 [get_ports {y_out[18]}]
set_load -pin_load 2 [get_ports {y_out[17]}]
set_load -pin_load 2 [get_ports {y_out[16]}]
set_load -pin_load 2 [get_ports {y_out[15]}]
set_load -pin_load 2 [get_ports {y_out[14]}]
set_load -pin_load 2 [get_ports {y_out[13]}]
set_load -pin_load 2 [get_ports {y_out[12]}]
set_load -pin_load 2 [get_ports {y_out[11]}]
set_load -pin_load 2 [get_ports {y_out[10]}]
set_load -pin_load 2 [get_ports {y_out[9]}]
set_load -pin_load 2 [get_ports {y_out[8]}]
set_load -pin_load 2 [get_ports {y_out[7]}]
set_load -pin_load 2 [get_ports {y_out[6]}]
set_load -pin_load 2 [get_ports {y_out[5]}]
set_load -pin_load 2 [get_ports {y_out[4]}]
set_load -pin_load 2 [get_ports {y_out[3]}]
set_load -pin_load 2 [get_ports {y_out[2]}]
set_load -pin_load 2 [get_ports {y_out[1]}]
set_load -pin_load 2 [get_ports {y_out[0]}]
set_load -pin_load 2 [get_ports valid_out]
set_load -pin_load 2 [get_ports scan_out]
create_clock [get_ports clk]  -period 208.333  -waveform {0 104.166}
set_clock_uncertainty -setup 1  [get_clocks clk]
set_clock_uncertainty -hold 0.1  [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_input_delay -clock clk  -clock_fall  -max 40  [get_ports pdm_in]
set_input_delay -clock clk  -clock_fall  -min 18  [get_ports pdm_in]
set_input_delay -clock clk  -max 20  [get_ports rst]
set_input_delay -clock clk  -min 0  [get_ports rst]
set_input_delay -clock clk  -max 20  [get_ports scan_en]
set_input_delay -clock clk  -min 0  [get_ports scan_en]
set_input_delay -clock clk  -max 20  [get_ports scan_in]
set_input_delay -clock clk  -min 0  [get_ports scan_in]
set_output_delay -clock clk  -max 20  [get_ports {y_out[18]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[18]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[17]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[17]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[16]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[16]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[15]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[15]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[14]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[14]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[13]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[13]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[12]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[12]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[11]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[11]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[10]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[10]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[9]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[9]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[8]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[8]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[7]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[7]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[6]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[6]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[5]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[5]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[4]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[4]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[3]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[3]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[2]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[2]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[1]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[1]}]
set_output_delay -clock clk  -max 20  [get_ports {y_out[0]}]
set_output_delay -clock clk  -min 0  [get_ports {y_out[0]}]
set_output_delay -clock clk  -max 20  [get_ports valid_out]
set_output_delay -clock clk  -min 0  [get_ports valid_out]
set_output_delay -clock clk  -max 20  [get_ports scan_out]
set_output_delay -clock clk  -min 0  [get_ports scan_out]
set_input_transition -max 0.1  [get_ports rst]
set_input_transition -min 0.1  [get_ports rst]
set_input_transition -max 0.1  [get_ports pdm_in]
set_input_transition -min 0.1  [get_ports pdm_in]
set_input_transition -max 0.1  [get_ports scan_en]
set_input_transition -min 0.1  [get_ports scan_en]
set_input_transition -max 0.1  [get_ports scan_in]
set_input_transition -min 0.1  [get_ports scan_in]
